name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"

      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"

      - name: echo if not skip
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message),' '), '#skip')}}
        run: echo "Main and not skipped"

      - name: Get formatted date
        id: format_date
        run: |
          DATE="2024-11-25T10:35:02+02:00"
          FORMATTED_DATE=$(date -d "$DATE" +"%A %H:%M")
          echo "Formatted date: $FORMATTED_DATE"
          echo "FORMATTED_DATE=$FORMATTED_DATE" >> $GITHUB_ENV  # Set formatted date as environment variable

      - name: echo date
        env:
          MSG: "Severity: Informational ${{ env.FORMATTED_DATE }}"
        run: echo ${{ env.MSG }}"
