name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"

      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"

      - name: echo if not skip
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message),' '), '#skip')}}
        run: echo "Main and not skipped"

      - name: Notify Discord on success
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GitHub Actions
          DISCORD_EMBEDS: |
            [{
              "title": "Success!",
              "color": 32768,
              "description": "Commit ${{toJson(github.event.commits[0].id)}} passed the tests.",
            }]
        uses: Ilshidur/action-discord@master
        with:
          args: "Test success"

      - name: Trigger an error
        run: nonexistent-command

      - name: Notify Discord on failure
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GitHub Actions
          DISCORD_EMBEDS: |
            [{
              "title": "Build failed!",
              "color": 16711680,
              "description": "Commit ${{github.event.commits[0].id || 'Unknown commit'}} caused the build to fail.",
              "footer": {
                "text": "Severity: Error | Check logs for more information."
              }
            }]
        uses: "Ilshidur/action-discord@master"
        with:
          args: "Commit ${{github.event.commits[0].id || 'Unknown commit'}} failed tests."
