name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"

      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"

      - name: echo if not skip
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message),' '), '#skip')}}
        run: echo "Main and not skipped"

      - name: Notify Discord on success
        if: success()
        env:
          DATE: "2024-11-25T10:35:02+02:00"
          FORMATTED_DATE: $(date -d "$DATE" +"%A %H:%M")
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GitHub Actions
          DISCORD_EMBEDS: |
            [{
              "title": "Build succeeded!",
              "color": 32768,
              "description": "to https://full-stack-open-pokedex-8pfy.onrender.com by ${{github.event.commits[0].committer.name || 'Unknown commit'}} passed the tests.", 
              "footer": {
                "text": "Severity: Informational. $FORMATTED_DATE"
              }
            }]
        uses: Ilshidur/action-discord@master
        with:
          args: "A new version of Pokedex deployed"

      - name: Trigger an error
        run: nonexistent-command

      - name: Notify Discord on failure
        if: failure()
        env:
          DATE: "2024-11-25T10:35:02+02:00"
          FORMATTED_DATE: $(date -d "$DATE" +"%A %H:%M")
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GitHub Actions
          DISCORD_EMBEDS: |
            [{
              "title": "Build failed!",
              "color": 16711680,
              "description": "Commit ${{github.event.commits[0].url || 'Unknown commit'}} by ${{github.event.commits[0].committer.name || 'Unknown commit'}} broke the build :(", 
              "footer": {
                "text": "Severity: Error $FORMATTED_DATE"
              }
            }]
        uses: "Ilshidur/action-discord@master"
        with:
          args: "Buld Failed!"
